### ISSUE TITLE
BugSack report

### ISSUE THREAD

**Issue by Ci303** [Zwyk/Z-Mission-Table-Win-Estimator#1] opened 2021-01-04 21:44 UTC
Hey there, thanks for the WA! 
Getting this error when assigning Companions to level 9 Elite Adventure,  **Rot-Heart's Final Rest** (Venthyr Covenant). Estimator gets stuck on 'Add Troops'.

```
3x [string "--[==[ Error in 'Z Mission Table Win Estima..."]:97: attempt to perform arithmetic on field 'HP' (a nil value)
[string "--[==[ Error in 'Z Mission Table Win Estimator':'initialization' ]==] return function() aura_env.matches = {}

aura_env.matches["enUS"] = {
    {text="dealing %d+ .*damage to all", type="dmg-aoe", family="dealing"},
    {text="all enemies.*, dealing %d+", type="dmg-aoe", family="dealing"},
    {text="all enemies.* for %d+ .*damage", type="dmg-aoe", family="dealing"},
    {text="dealing %d+ .*damage in a cone", type="dmg-cone", family="dealing"},
    {text="in a cone.*, dealing %d+ .*damage", type="dmg-cone", family="dealing"},
    {text="dealing %d+ .*damage for .*", type="dot", family="dealing"},
    {text="adjacent enemies.*, dealing %d+ .*damage", type="dmg-adj", family="dealing"},
    {text="dealing %d+ .*damage to .*adjacent enemies", type="dmg-adj", family="dealing"},
    {text="dealing %d+ .*damage to both", type="dmg-pierce", family="dealing"},
    {text="dealing %d+ .*damage to them and an enemy behind", type="dmg-pierce", family="dealing"},
    {text="dealing a %d+", type="dmg", family="dealing"},
    {text="dealing %d+", type="dmg", family="dealing"},
    
    {text="deals %d+ .*damage .*each .* for .*", type="dot", family="deals"},
    {text="each turn.*deals %d+%% maximum health .*damage to all", type="dot-pct-aoe", family="deals"},
    {text="deals %d+", type="dmg", family="deals"},
    
    {text="and then %d+ .*damage", type="dmg"},
    {text="and %d+ with the second", type="dmg"},
    {text=", then %d+, then %d+, then %d+%.", type="dmg"},
    {text=", then %d+, then %d+, then %d+%.", type="dmg"},
    {text=", then %d+%.", type="dmg"},
    {text="hitting them for %d+ .*damage", type="dmg"},
    {text="closest enemy for %d+%% of their maximum hit points", type="dmg-pct"},
    
    {text="damage over time effect for %d+", type="dot"},
    {text="additional %d+ .*damage .* round", type="dot"},
    {text="additional %d+ .*damage .* turn", type="dot"},
    {text="and %d+ .*damage for .* .*", type="dot"},
    {text="bleed for %d+ for .*", type="dot"},
    
    {text="inflicting %d+ .*damage .* round", type="dot-aoe"},
    
    {text="increases his damage.* by %d+", type="imp-flat"},
    {text="increasing their damage.* by %d+ ", type="imp-flat-all"},
    
    {text="increasing damage done by %d+%%", type="imp"},
    {text="increasing his damage by %d+%%", type="imp"},
    {text="buffing their damage by %d+%%", type="imp-all"},
    {text="increasing their damage by %d+%%", type="imp-all"},
    {text="adjacent allies, increasing all damage they deal by %d+%%", type="imp-adj"},
    {text="doubles the damage of all allies for %d+ rounds", type="imp-all-double"},
    
    {text="but reduce their damage by %d+%% for the next round", type="nerf"},
    
    {text="increasing damage taken by %d+%%", type="vulne"},
    {text="causing them to take %d+%% more damage", type="vulne"},
    {text="increasing the damage they take by %d+%%", type="vulne-all"},
    
    {text="each turn.*heal[s]? for %d+%% of maximum health", type="hot-pct", family="heals"},
    {text="heal[s]? all .*for %d+%% of their max", type="heal-pct-aoe", family="heals"},
    {text="heal[s]? all .*for %d+", type="heal-aoe", family="heals"},
    {text="heal[s]? .*for %d+", type="heal", family="heals"},
    
    {text="healing their.*for %d+", type="heal-aoe", family="healing"},
    {text="healing .*for %d+", type="heal", family="healing"},
    
    {text="and damage taken by %d+ for .*", type="hot"},
    {text="increases their maximum health by %d+%%", type="heal-pct"},
    
    {text="reducing the damage they take by %d+%%", type="prot"},
    {text="reducing all damage taken by %d+%%", type="prot-all"},
    {text="decreasing damage done by %d+%%", type="prot-all"},
    {text="reducing the damage .*allies take by %d+%%", type="prot-all"},
    {text="all allies take %d+%% less damage", type="prot-all"},
    {text="reducing their damage.* by %d+%%", type="prot-all"},
    {text="reduces their damage.* by %d+%%", type="prot-all"},
    
    {text="takes %d+%% reduced damage and protects all ranged allies", type="prot-self-ranged"},
}

aura_env.matches["enGB"] = aura_env.matches["enUS"]

aura_env.effects = function(text, matching, effect, cd, a, e)
    local damage, heal, modDmg, modDmgTaken = 0, 0, 1, 1
    
    local val = matching:match("%d+")
    local rounds = aura_env.roundsFromString(text, cd)
    local hitA = aura_env.nbHitAoe(text, a)
    local hitE = aura_env.nbHitAoe(text, e)
    local hitCone = aura_env.nbHitCone(e)
    local hitPierce = aura_env.nbHitPierce(e)
    local hitAdjA = aura_env.nbHitAdjacent(a)
    local hitAdjE = aura_env.nbHitAdjacent(e)
    
    if effect.type == "dmg" then damage = val/cd
    elseif effect.type == "dmg-aoe" then damage = val*hitE/cd
    elseif effect.type == "dmg-cone" then damage = val*hitCone/cd
    elseif effect.type == "dmg-adj" then damage = val*hitAdjE/cd
    elseif effect.type == "dmg-pierce" then damage = val*hitPierce/cd
    elseif effect.type == "dmg-pct" then damage = val/100*e.HP/e.tot*rounds/cd
    elseif effect.type == "dot" then damage = val*rounds/cd
    elseif effect.type == "dot-aoe" then damage = val*rounds*hitE/cd
    elseif effect.type == "dot-pct-aoe" then damage = val/100*e.HP*hitE/e.tot*rounds/cd
    elseif effect.type == "imp-flat" then damage = val*rounds/cd
    elseif effect.type == "imp-flat-all" then damage = val*a.tot*rounds/cd
        
    elseif effect.type == "imp" then modDmg = 1+val/100/a.tot*rounds/cd
    elseif effect.type == "imp-all" then modDmg = 1+val/100*rounds/cd
    elseif effect.type == "imp-all-double" then modDmg = 1+rounds/cd
    elseif effect.type == "imp-adj" then modDmg = 1+val/100*hitAdjA/a.tot*rounds/cd
    elseif effect.type == "vulne" then modDmg = 1+val/100/e.tot*rounds/cd
    elseif effect.type == "vulne-all" then modDmg = 1+val/100*rounds/cd
    elseif effect.type == "nerf" then modDmg = 1-val/100/a.tot*rounds/cd
        
    elseif effect.type == "heal" then heal = val/cd
    elseif effect.type == "hot" then heal = val*rounds/cd
    elseif effect.type == "heal-aoe" then heal = val*hitA/cd
    elseif effect.type == "heal-pct" then heal = val/100*a.hp/a.tot/cd
    elseif effect.type == "heal-pct-aoe" then heal = val/100*a.hp*hitA/a.tot/cd
    elseif effect.type == "hot-pct" then heal = val/100*a.hp/a.tot*rounds/cd
        
    elseif effect.type == "prot" then modDmgTaken = 1-val/100/a.tot*rounds/cd
    elseif effect.type == "prot-all" then modDmgTaken = 1-val/100*rounds/cd
    elseif effect.type == "prot-self-ranged" then modDmgTaken = 1-val/100*(math.min(a.melee,1)+a.ranged)/a.tot*rounds/cd
        
    end
    
    return damage, heal, modDmg, modDmgTaken
end

aura_env.spellEffects = function(text, cd, a, e)
    local damage, heal, modDmg, modDmgTaken = 0, 0, 1, 1
    
    cd = cd > 0 and cd or 1
    text = text:lower():gsub("-", "")
    
    local families = {}
    for _, effect in ipairs(aura_env.matches[GetLocale()]) do
        if (not effect.family or not families[effect.family]) then
            local matching = text:match(effect.text)
            if matching then
                local d,h,md,mdt = aura_env.effects(text, matching, effect, cd, a, e)
                damage = damage + d
                heal = heal + h
                modDmg = modDmg * md
                modDmgTaken = modDmgTaken * mdt
                
                if effect.family then
                    families[effect.family] = true
                end
            end
        end
    end
    
    return damage, heal, modDmg, modDmgTaken
end

aura_env.totPartyBonus = function(a, e)
    local damage, heal, modDmg, modDmgTaken = 0, 0, 1, 1
    if aura_env.matches[GetLocale()] then
        for _, frame in ipairs({a.container:GetChildren()}) do
            if frame.name ~= nil then
                for _, spell in ipairs(frame:GetAutoCombatSpells()) do
                    local d,h,md,mdt = aura_env.spellEffects(spell.description, spell.cooldown, a, e)
                    damage = damage + d
                    heal = heal + h
                    modDmg = modDmg * md
                    modDmgTaken = modDmgTaken * mdt
                end
            end
        end
    end
    return damage, heal, modDmg, modDmgTaken
end

aura_env.nbMeleeRanged = function(allies, enemies)
    local aMelee, aRanged, eMelee, eRanged = 0,0,0,0
    
    for _, frame in ipairs({allies:GetChildren()}) do
        if(frame.name) then
            if frame.boardIndex > 1 then aMelee = aMelee + 1
            else aRanged = aRanged + 1
            end
        end
    end
    
    for _, frame in ipairs({enemies:GetChildren()}) do
        if(frame.name) then
            if frame.boardIndex < 9 then eMelee = eMelee + 1
            else eRanged = eRanged + 1
            end
        end
    end
    
    return aMelee, aRanged, eMelee, eRanged
end

aura_env.roundsFromString = function(text, cd)
    local check = text:match("%d+ rounds")
    or text:match("%d+ turns")
    return 
    (check and string.match(check, "%d+"))
    or (((text:match("one turn") or text:match("one round")) and 1)
        or ((text:match("two turns") or text:match("two rounds")) and 2)
        or ((text:match("three turns") or text:match("three rounds")) and 3)
        or ((text:match("four turns") or text:match("four rounds")) and 4))
    or cd
end

aura_env.nbHitAoe = function(text, hit)
    if text:match("melee") or text:match("front") then return hit.melee
    elseif text:match("ranged") or text:match("back") then return hit.ranged
    elseif text:match("a line") then return aura_env.nbHitPierce(hit)
    else return hit.tot
    end
end

aura_env.nbHitCone = function(hit)
    return 1 + (hit.melee > 0 and math.min(hit.ranged, 2) or 0)
end

aura_env.nbHitAdjacent = function(hit)
    return math.min(hit.melee, hit.ranged, 3)
end

aura_env.nbHitPierce = function(hit)
    return math.min(hit.melee, 1) + math.min(hit.ranged, 1)
end

if not aura_env.region.hook then
    aura_env.region.hook = true
    local func = function() 
        C_Timer.After(0.1, function() WeakAuras.ScanEvents("GO_FARM_ANIME", true) end)
    end
    
    LoadAddOn("Blizzard_GarrisonUI")
    
    CovenantMissionFrame.MissionTab.MissionPage.Board:HookScript('OnShow', func)
    CovenantMissionFrame.MissionTab.MissionPage.Board:HookScript('OnHide', func)
end
 end"]:136: in function `spellEffects'
[string "--[==[ Error in 'Z Mission Table Win Estimator':'initialization' ]==] return function() aura_env.matches = {}

aura_env.matches["enUS"] = {
    {text="dealing %d+ .*damage to all", type="dmg-aoe", family="dealing"},
    {text="all enemies.*, dealing %d+", type="dmg-aoe", family="dealing"},
    {text="all enemies.* for %d+ .*damage", type="dmg-aoe", family="dealing"},
    {text="dealing %d+ .*damage in a cone", type="dmg-cone", family="dealing"},
    {text="in a cone.*, dealing %d+ .*damage", type="dmg-cone", family="dealing"},
    {text="dealing %d+ .*damage for .*", type="dot", family="dealing"},
    {text="adjacent enemies.*, dealing %d+ .*damage", type="dmg-adj", family="dealing"},
    {text="dealing %d+ .*damage to .*adjacent enemies", type="dmg-adj", family="dealing"},
    {text="dealing %d+ .*damage to both", type="dmg-pierce", family="dealing"},
    {text="dealing %d+ .*damage to them and an enemy behind", type="dmg-pierce", family="dealing"},
    {text="dealing a %d+", type="dmg", family="dealing"},
    {text="dealing %d+", type="dmg", family="dealing"},
    
    {text="deals %d+ .*damage .*each .* for .*", type="dot", family="deals"},
    {text="each turn.*deals %d+%% maximum health .*damage to all", type="dot-pct-aoe", family="deals"},
    {text="deals %d+", type="dmg", family="deals"},
    
    {text="and then %d+ .*damage", type="dmg"},
    {text="and %d+ with the second", type="dmg"},
    {text=", then %d+, then %d+, then %d+%.", type="dmg"},
    {text=", then %d+, then %d+, then %d+%.", type="dmg"},
    {text=", then %d+%.", type="dmg"},
    {text="hitting them for %d+ .*damage", type="dmg"},
    {text="closest enemy for %d+%% of their maximum hit points", type="dmg-pct"},
    
    {text="damage over time effect for %d+", type="dot"},
    {text="additional %d+ .*damage .* round", type="dot"},
    {text="additional %d+ .*damage .* turn", type="dot"},
    {text="and %d+ .*damage for .* .*", type="dot"},
    {text="bleed for %d+ for .*", type="dot"},
    
    {text="inflicting %d+ .*damage .* round", type="dot-aoe"},
    
    {text="increases his damage.* by %d+", type="imp-flat"},
    {text="increasing their damage.* by %d+ ", type="imp-flat-all"},
    
    {text="increasing damage done by %d+%%", type="imp"},
    {text="increasing his damage by %d+%%", type="imp"},
    {text="buffing their damage by %d+%%", type="imp-all"},
    {text="increasing their damage by %d+%%", type="imp-all"},
    {text="adjacent allies, increasing all damage they deal by %d+%%", type="imp-adj"},
    {text="doubles the damage of all allies for %d+ rounds", type="imp-all-double"},
    
    {text="but reduce their damage by %d+%% for the next round", type="nerf"},
    
    {text="increasing damage taken by %d+%%", type="vulne"},
    {text="causing them to take %d+%% more damage", type="vulne"},
    {text="increasing the damage they take by %d+%%", type="vulne-all"},
    
    {text="each turn.*heal[s]? for %d+%% of maximum health", type="hot-pct", family="heals"},
    {text="heal[s]? all .*for %d+%% of their max", type="heal-pct-aoe", family="heals"},
    {text="heal[s]? all .*for %d+", type="heal-aoe", family="heals"},
    {text="heal[s]? .*for %d+", type="heal", family="heals"},
    
    {text="healing their.*for %d+", type="heal-aoe", family="healing"},
    {text="healing .*for %d+", type="heal", family="healing"},
    
    {text="and damage taken by %d+ for .*", type="hot"},
    {text="increases their maximum health by %d+%%", type="heal-pct"},
    
    {text="reducing the damage they take by %d+%%", type="prot"},
    {text="reducing all damage taken by %d+%%", type="prot-all"},
    {text="decreasing damage done by %d+%%", type="prot-all"},
    {text="reducing the damage .*allies take by %d+%%", type="prot-all"},
    {text="all allies take %d+%% less damage", type="prot-all"},
    {text="reducing their damage.* by %d+%%", type="prot-all"},
    {text="reduces their damage.* by %d+%%", type="prot-all"},
    
    {text="takes %d+%% reduced damage and protects all ranged allies", type="prot-self-ranged"},
}

aura_env.matches["enGB"] = aura_env.matches["enUS"]

aura_env.effects = function(text, matching, effect, cd, a, e)
    local damage, heal, modDmg, modDmgTaken = 0, 0, 1, 1
    
    local val = matching:match("%d+")
    local rounds = aura_env.roundsFromString(text, cd)
    local hitA = aura_env.nbHitAoe(text, a)
    local hitE = aura_env.nbHitAoe(text, e)
    local hitCone = aura_env.nbHitCone(e)
    local hitPierce = aura_env.nbHitPierce(e)
    local hitAdjA = aura_env.nbHitAdjacent(a)
    local hitAdjE = aura_env.nbHitAdjacent(e)
    
    if effect.type == "dmg" then damage = val/cd
    elseif effect.type == "dmg-aoe" then damage = val*hitE/cd
    elseif effect.type == "dmg-cone" then damage = val*hitCone/cd
    elseif effect.type == "dmg-adj" then damage = val*hitAdjE/cd
    elseif effect.type == "dmg-pierce" then damage = val*hitPierce/cd
    elseif effect.type == "dmg-pct" then damage = val/100*e.HP/e.tot*rounds/cd
    elseif effect.type == "dot" then damage = val*rounds/cd
    elseif effect.type == "dot-aoe" then damage = val*rounds*hitE/cd
    elseif effect.type == "dot-pct-aoe" then damage = val/100*e.HP*hitE/e.tot*rounds/cd
    elseif effect.type == "imp-flat" then damage = val*rounds/cd
    elseif effect.type == "imp-flat-all" then damage = val*a.tot*rounds/cd
        
    elseif effect.type == "imp" then modDmg = 1+val/100/a.tot*rounds/cd
    elseif effect.type == "imp-all" then modDmg = 1+val/100*rounds/cd
    elseif effect.type == "imp-all-double" then modDmg = 1+rounds/cd
    elseif effect.type == "imp-adj" then modDmg = 1+val/100*hitAdjA/a.tot*rounds/cd
    elseif effect.type == "vulne" then modDmg = 1+val/100/e.tot*rounds/cd
    elseif effect.type == "vulne-all" then modDmg = 1+val/100*rounds/cd
    elseif effect.type == "nerf" then modDmg = 1-val/100/a.tot*rounds/cd
        
    elseif effect.type == "heal" then heal = val/cd
    elseif effect.type == "hot" then heal = val*rounds/cd
    elseif effect.type == "heal-aoe" then heal = val*hitA/cd
    elseif effect.type == "heal-pct" then heal = val/100*a.hp/a.tot/cd
    elseif effect.type == "heal-pct-aoe" then heal = val/100*a.hp*hitA/a.tot/cd
    elseif effect.type == "hot-pct" then heal = val/100*a.hp/a.tot*rounds/cd
        
    elseif effect.type == "prot" then modDmgTaken = 1-val/100/a.tot*rounds/cd
    elseif effect.type == "prot-all" then modDmgTaken = 1-val/100*rounds/cd
    elseif effect.type == "prot-self-ranged" then modDmgTaken = 1-val/100*(math.min(a.melee,1)+a.ranged)/a.tot*rounds/cd
        
    end
    
    return damage, heal, modDmg, modDmgTaken
end

aura_env.spellEffects = function(text, cd, a, e)
    local damage, heal, modDmg, modDmgTaken = 0, 0, 1, 1
    
    cd = cd > 0 and cd or 1
    text = text:lower():gsub("-", "")
    
    local families = {}
    for _, effect in ipairs(aura_env.matches[GetLocale()]) do
        if (not effect.family or not families[effect.family]) then
            local matching = text:match(effect.text)
            if matching then
                local d,h,md,mdt = aura_env.effects(text, matching, effect, cd, a, e)
                damage = damage + d
                heal = heal + h
                modDmg = modDmg * md
                modDmgTaken = modDmgTaken * mdt
                
                if effect.family then
                    families[effect.family] = true
                end
            end
        end
    end
    
    return damage, heal, modDmg, modDmgTaken
end

aura_env.totPartyBonus = function(a, e)
    local damage, heal, modDmg, modDmgTaken = 0, 0, 1, 1
    if aura_env.matches[GetLocale()] then
        for _, frame in ipairs({a.container:GetChildren()}) do
            if frame.name ~= nil then
                for _, spell in ipairs(frame:GetAutoCombatSpells()) do
                    local d,h,md,mdt = aura_env.spellEffects(spell.description, spell.cooldown, a, e)
                    damage = damage + d
                    heal = heal + h
                    modDmg = modDmg * md
                    modDmgTaken = modDmgTaken * mdt
                end
            end
        end
    end
    return damage, heal, modDmg, modDmgTaken
end

aura_env.nbMeleeRanged = function(allies, enemies)
    local aMelee, aRanged, eMelee, eRanged = 0,0,0,0
    
    for _, frame in ipairs({allies:GetChildren()}) do
        if(frame.name) then
            if frame.boardIndex > 1 then aMelee = aMelee + 1
            else aRanged = aRanged + 1
            end
        end
    end
    
    for _, frame in ipairs({enemies:GetChildren()}) do
        if(frame.name) then
            if frame.boardIndex < 9 then eMelee = eMelee + 1
            else eRanged = eRanged + 1
            end
        end
    end
    
    return aMelee, aRanged, eMelee, eRanged
end

aura_env.roundsFromString = function(text, cd)
    local check = text:match("%d+ rounds")
    or text:match("%d+ turns")
    return 
    (check and string.match(check, "%d+"))
    or (((text:match("one turn") or text:match("one round")) and 1)
        or ((text:match("two turns") or text:match("two rounds")) and 2)
        or ((text:match("three turns") or text:match("three rounds")) and 3)
        or ((text:match("four turns") or text:match("four rounds")) and 4))
    or cd
end

aura_env.nbHitAoe = function(text, hit)
    if text:match("melee") or text:match("front") then return hit.melee
    elseif text:match("ranged") or text:match("back") then return hit.ranged
    elseif text:match("a line") then return aura_env.nbHitPierce(hit)
    else return hit.tot
    end
end

aura_env.nbHitCone = function(hit)
    return 1 + (hit.melee > 0 and math.min(hit.ranged, 2) or 0)
end

aura_env.nbHitAdjacent = function(hit)
    return math.min(hit.melee, hit.ranged, 3)
end

aura_env.nbHitPierce = function(hit)
    return math.min(hit.melee, 1) + math.min(hit.ranged, 1)
end

if not aura_env.region.hook then
    aura_env.region.hook = true
    local func = function() 
        C_Timer.After(0.1, function() WeakAuras.ScanEvents("GO_FARM_ANIME", true) end)
    end
    
    LoadAddOn("Blizzard_GarrisonUI")
    
    CovenantMissionFrame.MissionTab.MissionPage.Board:HookScript('OnShow', func)
    CovenantMissionFrame.MissionTab.MissionPage.Board:HookScript('OnHide', func)
end
 end"]:158: in function `totPartyBonus'
[string "--[==[ Error in 'Z Mission Table Win Estimator' ]==] return function(s, ev, ...)
    if ev == "GARRISON_MISSION_NPC_OPENED"
    or ev == "GARRISON_SHIPYARD_NPC_CLOSED"
    or ev == "GARRISON_FOLLOWER_LIST_UPDATE"
    then
        C_Timer.After(0.1, function() WeakAuras.ScanEvents("GO_FARM_ANIME", true) end)
    elseif ev == "GO_FARM_ANIME" and ... then
        if CovenantMissionFrame
        and CovenantMissionFrame:IsVisible()
        and CovenantMissionFrame.MissionTab
        and CovenantMissionFrame.MissionTab.MissionPage
        and CovenantMissionFrame.MissionTab.MissionPage.Stage
        and CovenantMissionFrame.MissionTab.MissionPage.Stage:IsVisible()
        and CovenantMissionFrame.MissionTab.MissionPage.Board
        and CovenantMissionFrame.MissionTab.MissionPage.Board:IsVisible()
        then
            local stage = CovenantMissionFrame.MissionTab.MissionPage.Stage
            local board = CovenantMissionFrame.MissionTab.MissionPage.Board
            local percent = 0
            
            local a, e = {}, {}
            a.hp = board.AllyHealthValue and board.AllyHealthValue:GetText():gsub(',','') or 0
            a.dmg = board.AllyPowerValue and board.AllyPowerValue:GetText():gsub(',','') or 0
            
            if tonumber(a.dmg) > 0 then
                e.hp = stage.EnemyHealthValue and stage.EnemyHealthValue:GetText():gsub(',','') or 0
                e.dmg = stage.EnemyPowerValue and stage.EnemyPowerValue:GetText():gsub(',','') or 0
                
                a.container = CovenantMissionFrame.MissionTab.MissionPage.Board.FollowerContainer
                e.container = CovenantMissionFrame.MissionTab.MissionPage.Board.EnemyContainer
                
                a.melee, a.ranged, e.melee, e.ranged = aura_env.nbMeleeRanged(a.container, e.container)
                a.tot = a.melee + a.ranged
                e.tot = e.melee + e.ranged
                
                a.dmgBonus, a.heal, a.dmgMod, a.dmgTakenMod = aura_env.totPartyBonus(a, e)
                e.dmgBonus, e.heal, e.dmgMod, e.dmgTakenMod = aura_env.totPartyBonus(e, a)
                
                a.dmgTot = (a.dmg + a.dmgBonus) * a.dmgMod * e.dmgTakenMod
                e.dmgTot = (e.dmg + e.dmgBonus) * e.dmgMod * a.dmgTakenMod
                
                a.dmgEff = a.dmgTot-e.heal
                e.dmgEff = e.dmgTot-a.heal
                
                if a.dmgEff < 1 then
                    e.dmgEff = e.dmgEff + (a.dmgEff < 0 and (-a.dmgEff+1) or (1-a.dmgEff))
                    a.dmgEff = 1
                end
                if e.dmgEff < 1 then
                    a.dmgEff = a.dmgEff + (e.dmgEff < 0 and (-e.dmgEff+1) or (1-e.dmgEff))
                    e.dmgEff = 1
                end
                
                a.estWin = e.hp/a.dmgEff
                e.estWin = a.hp/e.dmgEff
                
                percent = e.estWin^2/(e.estWin^2+a.estWin^2)
                percent = math.floor(percent*100+0.5)
            end
            
            s[""] = {
                percent = percent,
                select = tonumber(a.dmg) == 0,
                progressType = "static",
                value = percent,
                changed = true,
                show = true,
            }
            return true
        elseif s[""] then
            s[""] = {
                changed = true,
                show = false,
            }
            return true
        end
    end
end"]:37: in function <[string "--[==[ Error in 'Z Mission Table Win Estima..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:541: in function <WeakAuras\GenericTrigger.lua:534>
[string "@WeakAuras\GenericTrigger.lua"]:730: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:691: in function `ScanEvents'
[string "--[==[ Error in 'Z Mission Table Win Estimator' ]==] return function(s, ev, ...)
    if ev == "GARRISON_MISSION_NPC_OPENED"
    or ev == "GARRISON_SHIPYARD_NPC_CLOSED"
    or ev == "GARRISON_FOLLOWER_LIST_UPDATE"
    then
        C_Timer.After(0.1, function() WeakAuras.ScanEvents("GO_FARM_ANIME", true) end)
    elseif ev == "GO_FARM_ANIME" and ... then
        if CovenantMissionFrame
        and CovenantMissionFrame:IsVisible()
        and CovenantMissionFrame.MissionTab
        and CovenantMissionFrame.MissionTab.MissionPage
        and CovenantMissionFrame.MissionTab.MissionPage.Stage
        and CovenantMissionFrame.MissionTab.MissionPage.Stage:IsVisible()
        and CovenantMissionFrame.MissionTab.MissionPage.Board
        and CovenantMissionFrame.MissionTab.MissionPage.Board:IsVisible()
        then
            local stage = CovenantMissionFrame.MissionTab.MissionPage.Stage
            local board = CovenantMissionFrame.MissionTab.MissionPage.Board
            local percent = 0
            
            local a, e = {}, {}
            a.hp = board.AllyHealthValue and board.AllyHealthValue:GetText():gsub(',','') or 0
            a.dmg = board.AllyPowerValue and board.AllyPowerValue:GetText():gsub(',','') or 0
            
            if tonumber(a.dmg) > 0 then
                e.hp = stage.EnemyHealthValue and stage.EnemyHealthValue:GetText():gsub(',','') or 0
                e.dmg = stage.EnemyPowerValue and stage.EnemyPowerValue:GetText():gsub(',','') or 0
                
                a.container = CovenantMissionFrame.MissionTab.MissionPage.Board.FollowerContainer
                e.container = CovenantMissionFrame.MissionTab.MissionPage.Board.EnemyContainer
                
                a.melee, a.ranged, e.melee, e.ranged = aura_env.nbMeleeRanged(a.container, e.container)
                a.tot = a.melee + a.ranged
                e.tot = e.melee + e.ranged
                
                a.dmgBonus, a.heal, a.dmgMod, a.dmgTakenMod = aura_env.totPartyBonus(a, e)
                e.dmgBonus, e.heal, e.dmgMod, e.dmgTakenMod = aura_env.totPartyBonus(e, a)
                
                a.dmgTot = (a.dmg + a.dmgBonus) * a.dmgMod * e.dmgTakenMod
                e.dmgTot = (e.dmg + e.dmgBonus) * e.dmgMod * a.dmgTakenMod
                
                a.dmgEff = a.dmgTot-e.heal
                e.dmgEff = e.dmgTot-a.heal
                
                if a.dmgEff < 1 then
                    e.dmgEff = e.dmgEff + (a.dmgEff < 0 and (-a.dmgEff+1) or (1-a.dmgEff))
                    a.dmgEff = 1
                end
                if e.dmgEff < 1 then
                    a.dmgEff = a.dmgEff + (e.dmgEff < 0 and (-e.dmgEff+1) or (1-e.dmgEff))
                    e.dmgEff = 1
                end
                
                a.estWin = e.hp/a.dmgEff
                e.estWin = a.hp/e.dmgEff
                
                percent = e.estWin^2/(e.estWin^2+a.estWin^2)
                percent = math.floor(percent*100+0.5)
            end
            
            s[""] = {
                percent = percent,
                select = tonumber(a.dmg) == 0,
                progressType = "static",
                value = percent,
                changed = true,
                show = true,
            }
            return true
        elseif s[""] then
            s[""] = {
                changed = true,
                show = false,
            }
            return true
        end
    end
end"]:6: in function <[string "--[==[ Error in 'Z Mission Table Win Estima..."]:6>
```

**Comment by Zwyk** [comment] 2021-01-04 23:46
Thanks for the bug report, I pushed a fix the wago.io page! Please download the latest version and it should work as intended :)

**Closed as completed by Zwyk** 2021-01-04 23:46 UTC
